# -*- coding: utf-8 -*-
"""SpotifyNFT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13c5thXxYp2vDnjYZxaL4kXZ46IhmNfES
"""

import pandas as pd

# Load your Spotify data
df = pd.read_csv('/content/data.csv')

# Preview it
print("Shape:", df.shape)
df.head()

# Only keep songs with valid audio features
required_cols = ['valence', 'energy', 'danceability', 'acousticness', 'instrumentalness', 'tempo']
df = df.dropna(subset=required_cols)

# Double-check column types
df[required_cols].info()

df = df.sample(5000, random_state=42).reset_index(drop=True)

df['MoodScore'] = (
    df['valence'] * 0.4 +
    df['energy'] * 0.35 +
    df['danceability'] * 0.25
)

df['ReplayScore'] = (
    df['danceability'] * 0.3 +
    df['acousticness'] * 0.2 +
    (1 - df['instrumentalness']) * 0.25 +
    (1 - abs(df['tempo'] - 120) / 120) * 0.25  # Ideal tempo: 120 BPM
)

audio_features = ['valence', 'energy', 'danceability', 'tempo', 'acousticness', 'instrumentalness']
feature_means = df[audio_features].mean()

df['UniquenessScore'] = df[audio_features].sub(feature_means).abs().mean(axis=1)

df['NFT_Valuation'] = (
    df['MoodScore'] * 0.35 +
    df['ReplayScore'] * 0.35 +
    df['UniquenessScore'] * 0.3
)

df[['name', 'artists', 'MoodScore', 'ReplayScore', 'UniquenessScore', 'NFT_Valuation']].sort_values(
    by='NFT_Valuation', ascending=False
).head(10)

# Create NFT valuation tiers
def get_tier(score):
    if score >= 0.85:
        return 'Legendary'
    elif score >= 0.7:
        return 'Rare'
    else:
        return 'Common'

df['Tier'] = df['NFT_Valuation'].apply(get_tier)
df['Tier'].value_counts()

df.to_csv('sonic_currency_dataset.csv', index=False)

from google.colab import files
files.download('sonic_currency_dataset.csv')